version: '3'

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    restart: always
    hostname: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=mosaic_db
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_TCP_PORT=3306
    networks:
      - app-tier
  gateway:
    container_name: gateway-service
    build:
      context: .
      args:
        - APP=gateway
    restart: always
    ports:
      - 3001:3000
    networks:
      - app-tier
    depends_on:
      - projects
      - tasks
  projects:
    container_name: projects-service
    build:
      context: .
      args:
        - APP=projects
    restart: always
    ports:
      - 3002:3002
    networks:
      - app-tier
    depends_on:
      - mysql
  tasks:
    container_name: tasks-service
    build:
      context: .
      args:
        - APP=tasks
    restart: always
    ports:
      - 3003:3003
    networks:
      - app-tier
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
  resources:
    container_name: resources-service
    build:
      context: .
      args:
        - APP=resources
    restart: always
    ports:
      - 3004:3004
    networks:
      - app-tier
    environment:
      - MYSQL_DATABASE=resource_db
      - MYSQL_HOST=mosaic.c9guk4sq42cw.us-east-1.rds.amazonaws.com
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=xGLdfj9LP0xttgUxjb7t
      - MYSQL_TCP_PORT=3306
