version: "3"

networks:
  app-tier:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    restart: always
    hostname: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=mosaic_db
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_TCP_PORT=3306
    networks:
      - app-tier
  gateway:
    container_name: gateway-service
    build:
      context: .
      args:
        - APP=gateway
    restart: always
    ports:
      - 3001:3000
    networks:
      - app-tier
  projects:
    container_name: projects-service
    build:
      context: .
      args:
        - APP=projects
    restart: always
    ports:
      - 3002:3000
    networks:
      - app-tier
    depends_on:
      - mysql