version: "3"
services:
  gateway:
    container_name: gateway-service
    build:
      context: .
      args:
        - APP=gateway
    restart: always
    ports:
      - 3001:3000
  project:
    container_name: projects-service
    build:
      context: .
      args:
        - APP=projects
    restart: always
    ports:
      - 3002:3000
  tasks:
    container_name: tasks-service
    build:
      context: .
      args:
        - APP=tasks
    restart: always
    ports:
      - 3003:3000
  risks:
    container_name: risks-service
    build:
      context: .
      args:
        - APP=risks
    restart: always
    ports:
      - 3004:3000
  resources:
    container_name: resources-service
    build:
      context: .
      args:
        - APP=resources
    restart: always
    ports:
      - 3005:3000