version: '3'

networks:
  app-tier:
    driver: bridge

services:
  gateway:
    container_name: gateway-service
    build:
      context: .
      args:
        - APP=gateway
    restart: always
    ports:
      - 3001:3000
    networks:
      - app-tier
    # depends_on:
    #   - projects
    #   - tasks
  projects:
    container_name: projects-service
    build:
      context: .
      args:
        - APP=projects
    restart: always
    ports:
      - 3002:3002
    networks:
      - app-tier
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - MYSQL_DATABASE=project_db
      - MYSQL_HOST=mosaic.c9guk4sq42cw.us-east-1.rds.amazonaws.com
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=xGLdfj9LP0xttgUxjb7t
      - MYSQL_TCP_PORT=3306
  tasks:
    container_name: tasks-service
    build:
      context: .
      args:
        - APP=tasks
    restart: always
    ports:
      - 3003:3003
    networks:
      - app-tier
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - MYSQL_DATABASE=task_db
      - MYSQL_HOST=mosaic.c9guk4sq42cw.us-east-1.rds.amazonaws.com
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=xGLdfj9LP0xttgUxjb7t
      - MYSQL_TCP_PORT=3306
  resources:
    container_name: resources-service
    build:
      context: .
      args:
        - APP=resources
    restart: always
    ports:
      - 3004:3004
    networks:
      - app-tier
    environment:
      - MYSQL_DATABASE=resource_db
      - MYSQL_HOST=mosaic.c9guk4sq42cw.us-east-1.rds.amazonaws.com
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=xGLdfj9LP0xttgUxjb7t
      - MYSQL_TCP_PORT=3306
  risks:
    container_name: risks-service
    build:
      context: .
      args:
        - APP=risks
    restart: always
    ports:
      - 3005:3005
    networks:
      - app-tier
    environment:
      - MYSQL_DATABASE=risk_db
      - MYSQL_HOST=mosaic.c9guk4sq42cw.us-east-1.rds.amazonaws.com
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=xGLdfj9LP0xttgUxjb7t
      - MYSQL_TCP_PORT=3306